[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  # JWT için gizli anahtar - Netlify Dashboard'dan değiştirilebilir
  JWT_SECRET = "c78asdjkjoh890908dSA90cxuj9asd80asdujHa90sdua90sdu0jd9a0s0du9r5u"
  

# Netlify Functions yapılandırması
[[plugins]]
  package = "@netlify/plugin-nextjs"

# [functions]
#   node_bundler = "esbuild"
#   included_files = ["node_modules/.prisma/**", "prisma/**"]
#   external_node_modules = ["@prisma/client", "@prisma/engines"]
#   directory = "netlify/functions"

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# API isteklerini functions'a, diğer istekleri index.html'e yönlendir
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200
#   force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[create]
  publish_dir = "out"
  content_dir = "content"
  base_dir = "."
  dev_command = "npm run dev"
  build_command = "npm run build"

[create.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"
