[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  # JWT için gizli anahtar - Netlify Dashboard'dan değiştirilebilir
  JWT_SECRET = "netlify_dashboard_uzerinden_guncellenmeli"

# Netlify Functions yapılandırması
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/.prisma/client/**", "prisma/**"]
  external_node_modules = ["@prisma/client", "@prisma/engines"]

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# API isteklerini functions'a, diğer istekleri Next.js'e yönlendir
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200

[create]
  publish_dir = ".next"
  content_dir = "content"
  base_dir = "."
  dev_command = "npm run dev"
  build_command = "npm run build"

[create.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"
