[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/**"]

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Statik site için basit yönlendirme
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[create]
  publish_dir = "out"
  content_dir = "content"
  base_dir = "."
  dev_command = "npm run dev"
  build_command = "npm run build"

[create.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"
