[build]
  command = "npx prisma generate && npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/**/*", "node_modules/.prisma/**/*", "node_modules/@prisma/client/**/*"]
  
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Next.js için özel redirects ayarları
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = false

[create]
  publish_dir = ".next"
  content_dir = "content"
  base_dir = "."
  dev_command = "npm run dev"
  build_command = "npm run build"
  
[create.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true" 