[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"
  base = "."

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/**/*"]
  
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = false

[create]
  publish_dir = ".next"
  content_dir = "content"
  base_dir = "."
  dev_command = "npm run dev"
  build_command = "npm run build"
  
[create.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true" 