[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"
  base = "."

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/**/*"]
  
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 