[build]
  command = "npm run build"
  publish = ".next"
  base = "."

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  RUBY_VERSION = "2.7.2"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild" 